version: '3.8'

services:
  backend:
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    
  frontend:
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
